### ISSUE TITLE
PCA9546A error  i2cSelect.begin();

### ISSUE THREAD

**Issue by davidgardener** [hideakitai/PCA9547#2]
Hi, I am having an issue where I am trying to run the example for the PCA9546A

I am just trying to upload it without any changes and I am getting this error. I am fairly novice when it comes to programming. I dont see a .cpp file could that be why? I dont see anything called begin in the .h either, does it call that from the Wire.h? any help would be greatly appreciated!

Heres my error code

`
example-PCA9546A:9:15: error: 'class PCA9546A' has no member named 'begin'
     i2cSelect.begin(); // default addr : 0x70
               ^
exit status 1
'class PCA9546A' has no member named 'begin'
`

Many thanks!

**Comment by hideakitai** [comment]
This library is PCA9547. You are using PCA9546A. Please report it to the appropriate repository.

**Comment by davidgardener** [comment]
Hi, I think this is the correct repository, in the example folder there is an example for the PCA9546A, that is the one i am using. I cannot see a separate repository for a PCA9546A.

**Comment by hideakitai** [comment]
@davidgardener Oh... I'm sorry for that. I've fixed the issue in v0.1.1. Thank you for the issue report!

**Comment by friedl1977** [comment]
Hi - 

Still receive an error.  Please see below:

`../hal/b5som/pinmap_defines.h:46:13: expected ',' or '...' before numeric constant`

Hope you can help.  Chances are I am doing something wrong?

Regards, Friedl
